In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("styles.csv",on_bad_lines='skip')

In [6]:
df.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt
5,1855,Men,Apparel,Topwear,Tshirts,Grey,Summer,2011.0,Casual,Inkfruit Mens Chain Reaction T-shirt
6,30805,Men,Apparel,Topwear,Shirts,Green,Summer,2012.0,Ethnic,Fabindia Men Striped Green Shirt
7,26960,Women,Apparel,Topwear,Shirts,Purple,Summer,2012.0,Casual,Jealous 21 Women Purple Shirt
8,29114,Men,Accessories,Socks,Socks,Navy Blue,Summer,2012.0,Casual,Puma Men Pack of 3 Socks
9,30039,Men,Accessories,Watches,Watches,Black,Winter,2016.0,Casual,Skagen Men Black Watch

In [7]:
df['image'] = df.apply(lambda row: str(row['id']) + ".jpg", axis=1)

In [8]:
df.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,15970.jpg
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,39386.jpg
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,59263.jpg
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,21379.jpg
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,53759.jpg
5,1855,Men,Apparel,Topwear,Tshirts,Grey,Summer,2011.0,Casual,Inkfruit Mens Chain Reaction T-shirt,1855.jpg
6,30805,Men,Apparel,Topwear,Shirts,Green,Summer,2012.0,Ethnic,Fabindia Men Striped Green Shirt,30805.jpg
7,26960,Women,Apparel,Topwear,Shirts,Purple,Summer,2012.0,Casual,Jealous 21 Women Purple Shirt,26960.jpg
8,29114,Men,Accessories,Socks,Socks,Navy Blue,Summer,2012.0,Casual,Puma Men Pack of 3 Socks,29114.jpg
9,30039,Men,Accessories,Watches,Watches,Black,Winter,2016.0,Casual,Skagen Men Black Watch,30039.jpg

In [9]:
df = df.sample(frac=1)

In [10]:
df.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image
25886,4120,Unisex,Footwear,Shoes,Casual Shoes,Maroon,Summer,2011.0,Casual,Puma Unisex Lo Maroon Shoes,4120.jpg
14722,40485,Women,Footwear,Shoes,Sports Shoes,Grey,Fall,2012.0,Sports,Fila Women Grey Speed Lite Sports Shoes,40485.jpg
4785,1807,Men,Apparel,Topwear,Tshirts,Red,Fall,2010.0,Casual,Quechua Men G1 Techfresh Red T-shirt,1807.jpg
25800,4544,Men,Footwear,Shoes,Sports Shoes,Black,Summer,2011.0,Sports,Nike Men's Zoom For Black Shoe,4544.jpg
10015,45912,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Maxima Women Silver Dial Watch,45912.jpg
6450,22241,Men,Footwear,Shoes,Casual Shoes,Black,Summer,2011.0,Casual,ID Men Black Casual Shoe,22241.jpg
24143,53765,Men,Apparel,Topwear,Tshirts,Blue,Summer,2012.0,Casual,Puma Men Blue Striped T-shirt,53765.jpg
10217,31063,Women,Apparel,Topwear,Dupatta,Pink,Summer,2012.0,Ethnic,Fabindia Women Pink Silk Dupatta,31063.jpg
21429,44963,Men,Free Items,Free Gifts,Free Gifts,Gold,Winter,2016.0,Casual,Maxima Men Gold Dial Watch,44963.jpg
7862,33538,Women,Apparel,Bottomwear,Jeans,Black,Summer,2012.0,Casual,Wrangler Women Black Giselle Jeans,33538.jpg

In [11]:
df = df.sample(frac=1).reset_index(drop=True)

In [12]:
df.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image
0,29905,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Police Women Silver-Toned Dial Watch PL10813BS...,29905.jpg
1,4066,Men,Footwear,Shoes,Casual Shoes,Black,Summer,2011.0,Casual,Crocs Men's Tideline Canvas Black Shoe,4066.jpg
2,25746,Men,Accessories,Belts,Belts,Black,Winter,2015.0,Casual,Lino Perros Men Leather Black Belt,25746.jpg
3,1872,Men,Apparel,Topwear,Tshirts,White,Winter,2010.0,Casual,FIFA Mens 1962 World Cup White T-shirt,1872.jpg
4,27988,Men,Apparel,Innerwear,Briefs,Black,Summer,2016.0,Casual,Jockey ZONE Men Black Zone Briefs US17,27988.jpg
5,45795,Women,Footwear,Shoes,Heels,Black,Summer,2012.0,Casual,Senorita Women Black Sandals,45795.jpg
6,9689,Men,Apparel,Topwear,Tshirts,Blue,Fall,2011.0,Casual,Classic Polo Men Ikon Blue Polo Tshirts,9689.jpg
7,11506,Women,Footwear,Shoes,Heels,Grey,Winter,2015.0,Casual,Catwalk Women Lifestyle Grey Flats,11506.jpg
8,46255,Women,Apparel,Topwear,Tunics,Brown,Summer,2012.0,Casual,Fusion Beats Women Multi Coloured Tunic,46255.jpg
9,2923,Men,Apparel,Topwear,Tshirts,Green,Fall,2010.0,Casual,DUSG Men's Sariska Organic Olive T-shirt,2923.jpg

### Preparing the ImageDataGenerator for training the model

In [ ]:
from keras_preprocessing.image import ImageDataGenerator
batch_size = 256

In [ ]:
image_generator = ImageDataGenerator(
    validation_split=0.2
)

In [ ]:
training_generator = image_generator.flow_from_dataframe(
    dataframe=df,
    directory="images",
    x_col="image",
    y_col="masterCategory",
    target_size=(60,80),
    batch_size=batch_size,
    subset="training"
)

In [ ]:
validation_generator = image_generator.flow_from_dataframe(
    dataframe=df,
    directory="images",
    x_col="image",
    y_col="masterCategory",
    target_size=(60,80),
    batch_size=batch_size,
    subset="validation"
)

In [ ]:
classes = len(training_generator.class_indices)

In [ ]:
classes

### Initializing the Model using Neural Network

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

In [ ]:
#Initializing our model
classifier = Sequential()

In [ ]:
classifier.add(Conv2D(32,(3,3),input_shape = (60,80,3), activation = 'relu'))

classifier.add(MaxPooling2D(pool_size=(3, 3)))

classifier.add(Conv2D(32,(3,3), activation = 'relu'))

classifier.add(MaxPooling2D(pool_size=(3, 3)))
classifier.add(Flatten())

classifier.add(Dense(units=32,activation = 'relu'))
classifier.add(Dense(units=64,activation = 'relu'))
classifier.add(Dense(units=128,activation = 'relu'))
classifier.add(Dense(units=256,activation = 'relu'))
classifier.add(Dense(units=512,activation = 'relu'))

classifier.add(Dense(units=7,activation = 'softmax'))

In [ ]:
classifier.compile(optimizer='adam',
              loss="categorical_crossentropy",
              metrics=['accuracy'])

### Fitting Data in our Neural Network

In [ ]:
from math import ceil

In [ ]:
classifier.fit_generator(
    generator=training_generator,
    steps_per_epoch=ceil(0.8 * (df.shape[0] / batch_size)),

    validation_data=validation_generator,
    validation_steps=ceil(0.2 * (df.shape[0] / batch_size)),

    epochs=5,
    verbose=1
)

In [ ]:
loss, acc = classifier.evaluate_generator(validation_generator, steps=ceil(0.2 * (df.size / batch_size)))
print("\n%s: %.2f%%" % (classifier.metrics_names[1], acc * 100))

In [ ]:
### Saving the Model for further use

In [ ]:
classifier.save("model.h5")

In [ ]:
### Testing on our data

In [ ]:
import numpy as np
from keras.preprocessing import im

In [ ]:
filename = "15970.jpg"

In [ ]:
from keras.models import load_model
new_model = load_model('model.h5')
new_model.summary()

In [ ]:
test_image = image.load_img("images/"+filename,target_size=(60,80))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)

In [ ]:
result = new_model.predict(test_image)
print(result)

In [ ]:
val = np.argmax(result)
print(val)

In [ ]:
my_dict = training_generator.class_indices
key_list = list(my_dict.keys()) 
val_list = list(my_dict.values()) 
print(key_list[val])

In [ ]:
### Saving the Class IDs

In [ ]:
import pickle

In [ ]:
# save the model to disk
filename1 = 'key_list'
filename = 'val_list'

In [ ]:
pickle.dump(key_list, open(filename1, 'wb'))
pickle.dump(val_list, open(filename, 'wb'))